Repository gorhom/react-native-bottom-sheet, pull requests merged in 2021-01, with the labels that each got.

#135 fix: fixed interaction glitch
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheetHandleContainer/BottomSheetHandleContainer.tsx
  src/components/bottomSheetHandleContainer/types.d.ts
  src/hooks/useInteractivePanGestureHandler.ts
  src/hooks/useScrollableInternal.ts
Labels: v3

#137 feat: added over scroll and bouncing support
  example/src/components/contactItem/ContactItem.tsx
  example/src/components/contactList/ContactList.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/flatList/FlatList.tsx
  src/components/flatList/types.d.ts
  src/components/scrollView/ScrollView.tsx
  src/components/scrollView/types.d.ts
  src/components/sectionList/SectionList.tsx
  src/components/sectionList/types.d.ts
Labels: v3

#139 feat: added over drag support
  example/android/app/build.gradle
  example/src/components/contactList/ContactList.tsx
  example/src/components/handle/Handle.tsx
  example/src/screens/advanced/NavigatorExample.tsx
  example/src/screens/basic/BasicExamples.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheet/constants.ts
  src/components/bottomSheet/styles.ts
  src/components/bottomSheet/types.d.ts
  src/components/bottomSheetDebugView/ReText.tsx
  src/components/bottomSheetHandle/styles.ts
  src/components/flatList/FlatList.tsx
  src/components/scrollView/ScrollView.tsx
  src/components/sectionList/SectionList.tsx
  src/hooks/useBottomSheetSpringConfigs.ts
  src/hooks/useBottomSheetTimingConfigs.ts
  src/hooks/useInteractivePanGestureHandler.ts
  src/hooks/useScrollableInternal.ts
  src/index.ts
Labels: v3

#146 feat: allow control flashing scrollable on expand
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheet/constants.ts
  src/components/bottomSheet/types.d.ts
Labels: v3

#145 refactor: updated overScrollMode to be come overridable
  src/components/flatList/FlatList.tsx
  src/components/flatList/types.d.ts
  src/components/scrollView/ScrollView.tsx
  src/components/scrollView/types.d.ts
  src/components/sectionList/SectionList.tsx
  src/components/sectionList/types.d.ts
Labels: v3

#148 feat: added more gesture handler props
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheet/types.d.ts
  src/components/bottomSheetDraggableView/BottomSheetDraggableView.tsx
  src/contexts/internal.ts
Labels: v3

#150 Fix animated reaction for aimated values from props
  src/components/bottomSheet/BottomSheet.tsx
Labels: v3

#151 fix: fixed the glitch when snapping animation is running on android
  example/src/screens/advanced/ViewPagerExample.tsx
  src/components/bottomSheet/constants.ts
  src/components/bottomSheet/types.d.ts
  src/hooks/useScrollableInternal.ts
Labels: v3

#157 fix: fixed shouldMeasureHandleHeight evaluation
  src/components/bottomSheet/BottomSheet.tsx
Labels: v3

#158 fix: fixed shouldMeasureHandleHeight evaluation
  src/components/bottomSheet/BottomSheet.tsx
Labels: v2

#156 refactor: removed ContentWrapper from BottomSheet
  example/src/Dev.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheetContentWrapper/BottomSheetContentWrapper.android.tsx
  src/components/bottomSheetContentWrapper/BottomSheetContentWrapper.ios.tsx
  src/components/bottomSheetContentWrapper/index.ts
  src/components/bottomSheetContentWrapper/styles.ts
  src/components/bottomSheetContentWrapper/types.d.ts
  src/components/bottomSheetDraggableView/BottomSheetDraggableView.tsx
  src/components/bottomSheetHandleContainer/BottomSheetHandleContainer.tsx
  src/components/flatList/FlatList.tsx
  src/components/scrollView/ScrollView.tsx
  src/components/sectionList/SectionList.tsx
  src/contexts/internal.ts
  src/hooks/index.ts
  src/hooks/useTapGestureHandler.ts
Labels: v3

#166 refactor: remove getNode from scrollables refs
  src/components/flatList/FlatList.tsx
  src/components/scrollView/ScrollView.tsx
  src/components/sectionList/SectionList.tsx
Labels: v3

#169 fix: removed rounding up from useNormalizedSnapPoints hook.
  src/hooks/useNormalizedSnapPoints.ts
Labels: v3

#174 fix: updated gesture handler to sets all gesture states
  src/hooks/useInteractivePanGestureHandler.ts
Labels: v3

#175 fix: exp easing flickers on android
  src/components/bottomSheet/constants.ts
  src/components/bottomSheet/types.d.ts
  src/hooks/useBottomSheetTimingConfigs.ts
  src/utilities/easingExp.ts
Labels: v3

#176 refactor: updated bottom sheet layers
  example/src/App.tsx
  example/src/components/contactList/ContactList.tsx
  example/src/components/customBackground/CustomBackground.tsx
  example/src/components/customBackground/index.ts
  example/src/screens/Root.tsx
  example/src/screens/advanced/CustomBackgroundExample.tsx
  example/src/screens/advanced/NavigatorExample.tsx
  example/src/types.ts
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheet/styles.ts
Labels: v2

#177 fix: prevent rounding up normalised snap points
  src/hooks/useNormalizedSnapPoints.ts
Labels: v2

#186 fix: fixed over-drag implementation
  src/hooks/useInteractivePanGestureHandler.ts
Labels: v3

#189 feat: added style prop
  example/src/components/contactList/index.ts
  example/src/screens/advanced/BackdropExample.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheet/types.d.ts
Labels: v3

#199 chore: added no console eslint rule
  .eslintrc.js
  example/index.ts
  example/src/screens/DummyScreen.tsx
  example/src/screens/advanced/NavigatorExample.tsx
  example/src/screens/modal/SimpleExample.tsx
  example/src/screens/static/BasicExample.tsx
  example/src/screens/static/BasicExamples.tsx
  src/components/bottomSheet/BottomSheet.tsx
Labels: v2

#200 chore: updated reanimated to rc2
  example/ios/Podfile.lock
  example/package.json
  example/yarn.lock
  package.json
  yarn.lock
Labels: v3

#201 fix: removed rounding on evaluating position
  src/components/bottomSheet/BottomSheet.tsx
Labels: v3

#211 fix: allow backdrop style prop to override internal style
  src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
Labels: v3

#212 fix: allow backdrop style prop to override internal style
  src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
Labels: v2

#223 fix: fixed sheet visibility when handle provided null
  src/components/bottomSheet/BottomSheet.tsx
Labels: v3

#224 fix: fixed sheet visibility when handle provided null
  src/components/bottomSheet/BottomSheet.tsx
Labels: v2

#225 fix: removed onScroll event from BottomSheetScrollView
  src/components/bottomSheet/BottomSheet.tsx
  src/components/flatList/FlatList.tsx
  src/components/scrollView/ScrollView.tsx
  src/components/sectionList/SectionList.tsx
  src/contexts/internal.ts
  src/hooks/useScrollableInternal.ts
Labels: v2

#239 fix: stabilise animated callback node variables
  src/components/bottomSheet/BottomSheet.tsx
Labels: v2

#205 fix: prevent start animation when sheet is closing
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheetModal/BottomSheetModal.tsx
  src/types.d.ts
Labels: v2

#244 fix: prevent modal crash when navigating
  example/package.json
  example/yarn.lock
  package.json
  src/components/bottomSheetModal/BottomSheetModal.tsx
  yarn.lock
Labels: bottom-sheet-modal, v2
