Repository gorhom/react-native-bottom-sheet, pull requests merged in 2021-03, with the labels that each got.

#322 fix: prevent closing when sheet is out of screen
  src/components/bottomSheet/BottomSheet.tsx
Labels: v2

#315 fix: unmounting modals with navigation
  example/package.json
  example/src/screens/modal/StackExample.tsx
  example/yarn.lock
  package.json
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheetModal/BottomSheetModal.tsx
  src/components/bottomSheetModal/constants.ts
  src/components/bottomSheetModal/types.d.ts
  src/components/bottomSheetModalProvider/BottomSheetModalProvider.tsx
  src/constants.ts
  yarn.lock
Labels: v3

#325 docs: fix typo
  CONTRIBUTING.md
Labels: documentation

#333 feat: allow modify animation configs
  example/src/screens/modal/SimpleExample.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheetModal/BottomSheetModal.tsx
  src/constants.ts
  src/hooks/useBottomSheetSpringConfigs.ts
  src/hooks/useBottomSheetTimingConfigs.ts
  src/types.d.ts
  src/utilities/animate.ts
  src/utilities/index.ts
Labels: v3

#327 fix: updated modal unmounting handling
  example/ios/Podfile.lock
  example/package.json
  example/yarn.lock
  package.json
  src/components/bottomSheetModal/BottomSheetModal.tsx
  src/components/bottomSheetModal/types.d.ts
  src/components/bottomSheetModalProvider/BottomSheetModalProvider.tsx
  yarn.lock
Labels: v2

#345 chore: updated react-native to 64 and enable builds on M1 chip
  example/android/app/build.gradle
  example/android/app/src/debug/AndroidManifest.xml
  example/android/app/src/main/AndroidManifest.xml
  example/android/build.gradle
  example/android/gradle.properties
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/ios/BottomSheetExample.xcodeproj/project.pbxproj
  example/ios/Podfile
  example/ios/Podfile.lock
  example/package.json
  example/patches/react-native-pager-view+5.1.1.patch
  example/patches/react-native-reanimated+2.0.0-rc.3.patch
  example/yarn.lock
Labels: v3

#346 fix: improve modal dismissing
  example/ios/Podfile.lock
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheetModal/BottomSheetModal.tsx
  src/components/bottomSheetModalProvider/BottomSheetModalProvider.tsx
  src/hooks/useScrollable.ts
Labels: v3

#369 chore: updated example theming
  example/android/app/src/main/res/values/styles.xml
  example/ios/BottomSheetExample.xcodeproj/project.pbxproj
  example/ios/BottomSheetExample/AppDelegate.mm
  example/ios/BottomSheetExample/LaunchScreen.storyboard
  example/package.json
  example/patches/react-native-pager-view+5.1.1.patch
  example/patches/react-native-tab-view+2.15.2.patch
  example/src/App.tsx
  example/src/Perf.tsx
  example/src/components/appearanceProvider/AppearanceProvider.tsx
  example/src/components/appearanceProvider/index.ts
  example/src/components/blurredBackground/BlurredBackground.tsx
  example/src/components/button/Button.tsx
  example/src/components/contactList/ContactList.tsx
  example/src/components/contactListContainer/ContactListContainer.tsx
  example/src/components/locationDetails/LocationDetails.tsx
  example/src/components/locationDetailsHandle/LocationDetailsHandle.tsx
  example/src/components/locationItem/LocationItem.tsx
  example/src/components/searchHandle/SearchHandle.tsx
  example/src/components/text/Text.tsx
  example/src/components/text/index.ts
  example/src/components/weather/Weather.tsx
  example/src/contexts/AppearanceContext.ts
  example/src/contexts/index.ts
  example/src/hooks/index.ts
  example/src/hooks/useAppearance.ts
  example/src/screens/DummyScreen.tsx
  example/src/screens/advanced/CustomBackgroundExample.tsx
  example/src/screens/advanced/CustomHandleExample.tsx
  example/src/screens/advanced/NavigatorExample.tsx
  example/src/screens/basic/BasicExamples.tsx
  example/src/screens/index.ts
  example/src/screens/modal/StackExample.tsx
  example/src/screens/screens.ts
  example/src/types.d.ts
  example/yarn.lock
Labels: v3

#361 feat: support new prop for BottomSheetBackdrop, "pressBehavior"
  example/src/screens/advanced/BackdropExample.tsx
  example/src/screens/advanced/MapExample.tsx
  example/src/screens/modal/BackdropExample.tsx
  src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
  src/components/bottomSheetBackdrop/constants.ts
  src/components/bottomSheetBackdrop/types.d.ts
  src/components/bottomSheetBackdrop/usePressBehavior.ts
Labels: v3

#373 feat: support new prop for BottomSheetBackdrop, "pressBehavior"
  example/src/screens/advanced/BackdropExample.tsx
  example/src/screens/modal/BackdropExample.tsx
  src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
  src/components/bottomSheetBackdrop/constants.ts
  src/components/bottomSheetBackdrop/types.d.ts
  src/components/bottomSheetBackdrop/usePressBehavior.ts
  src/hooks/index.ts
Labels: v2

#334 feat: added keyboard handling
  example/ios/BottomSheetExample.xcodeproj/project.pbxproj
  example/ios/Podfile.lock
  example/src/Dev.tsx
  example/src/components/contactList/ContactList.tsx
  example/src/components/searchHandle/SearchHandle.tsx
  example/src/screens/advanced/KeyboardHandlingExample.tsx
  example/src/screens/integrations/MapExample.tsx
  example/src/screens/integrations/NavigatorExample.tsx
  example/src/screens/integrations/ViewPagerExample.tsx
  example/src/screens/screens.ts
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheet/constants.ts
  src/components/bottomSheet/types.d.ts
  src/components/bottomSheetDebugView/BottomSheetDebugView.tsx
  src/components/bottomSheetDebugView/ReText.tsx
  src/components/bottomSheetDebugView/styles.ts
  src/components/bottomSheetDraggableView/BottomSheetDraggableView.tsx
  src/components/bottomSheetTextInput/BottomSheetTextInput.tsx
  src/components/bottomSheetTextInput/index.ts
  src/components/bottomSheetTextInput/types.ts
  src/constants.ts
  src/contexts/internal.ts
  src/hooks/index.ts
  src/hooks/useBottomSheetSpringConfigs.ts
  src/hooks/useBottomSheetTimingConfigs.ts
  src/hooks/useInteractivePanGestureHandler.ts
  src/hooks/useKeyboard.ts
  src/hooks/useScrollable.ts
  src/hooks/useScrollableInternal.ts
  src/index.ts
  src/utilities/animate.ts
  src/utilities/getKeyboardAnimationConfigs.ts
  src/utilities/index.ts
Labels: v3
