Repository gorhom/react-native-bottom-sheet, pull requests merged in 2022-04, with the labels that each got.

#793 Fix BottomSheetBackdrop "falsey" defaults
  example/src/screens/advanced/BackdropExample.tsx
  src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
  src/components/bottomSheetBackdrop/types.d.ts
  src/contexts/external.ts
Labels: v4

#740 feat: add useBottomSheetInternal_unsafe & useBottomSheetModalInternal…
  src/hooks/useBottomSheetInternal.ts
  src/hooks/useBottomSheetModalInternal.ts
Labels: v4

#776 update link example code
  docs/modal/getting-started.mdx
Labels: documentation

#875 Update keyboardBehavior type
  docs/props.md
Labels: no-pr-activity
