Repository gorhom/react-native-bottom-sheet, pull requests merged in 2023-07, with the labels that each got.

#1445 chore: updated expo and react native deps
  example/app/package.json
  example/bare/ios/Podfile.lock
  example/bare/package.json
  example/expo/package.json
  src/components/bottomSheetModal/types.d.ts
Labels: v5

#1427 fix: invalid prop type
  docs/props.md
Labels: documentation

#1420 fix: keyboard on focus
  src/components/bottomSheetContainer/BottomSheetContainer.tsx
Labels: v4, v5
