Repository gorhom/react-native-bottom-sheet, pull requests merged in 2023-06, with the labels that each got.

#1392 fix: resume close animation when container gets resized (#1374)
  src/components/bottomSheet/BottomSheet.tsx
Labels: v4

#1412 chore: updated react native and other deps
  .eslintrc.js
  example/bare/android/app/build.gradle
  example/bare/android/app/src/main/java/dev/gorhom/bottomsheet/MainActivity.java
  example/bare/android/build.gradle
  example/bare/android/gradle.properties
  example/bare/android/gradle/wrapper/gradle-wrapper.properties
  example/bare/android/gradlew
  example/bare/android/settings.gradle
  example/bare/ios/BottomSheetExample.xcodeproj/project.pbxproj
  example/bare/ios/BottomSheetExample/AppDelegate.mm
  example/bare/ios/Podfile
  example/bare/ios/Podfile.lock
  example/bare/metro.config.js
  example/bare/package.json
  example/expo/package.json
  package.json
  yarn.lock
Labels: v5

#1394 mock BottomSheet list with ReactNative list equivalent
  mock.js
Labels: v4, v5

#1383 Update getting-started.mdx
  docs/modal/getting-started.mdx
Labels: documentation

#1309 fix(bottom-sheet-modal): behind native modal view
  src/components/bottomSheetModal/BottomSheetModal.tsx
  src/components/bottomSheetModal/types.d.ts
Labels: v4, v5

#1333 Update react-naigation.md
  docs/guides/react-naigation.md
Labels: no-pr-activity

#1352 docs: update present method
  docs/modal/methods.md
Labels: no-pr-activity
