Repository gorhom/react-native-bottom-sheet, pull requests merged in 2023-09, with the labels that each got.

#1513 feat: added dynamic sizing
  example/app/src/screens/advanced/DynamicSnapPointExample.tsx
  example/app/src/screens/modal/DynamicSnapPointExample.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/bottomSheet/constants.ts
  src/components/bottomSheet/types.d.ts
  src/components/bottomSheetScrollable/createBottomSheetScrollableComponent.tsx
  src/components/bottomSheetView/BottomSheetView.tsx
  src/contexts/internal.ts
  src/hooks/useBottomSheetDynamicSnapPoints.ts
  src/hooks/useNormalizedSnapPoints.ts
  src/hooks/usePropsValidator.ts
  src/utilities/normalizeSnapPoint.ts
Labels: v4

#1479 fix(bottomSheet): snapPoint type
  src/components/bottomSheet/types.d.ts
  src/components/bottomSheetContainer/BottomSheetContainer.tsx
  src/hooks/useGestureEventsHandlersDefault.tsx
Labels: v4, v5

#1512 fix: use correct link, grammar
  docs/getting-started.mdx
Labels: documentation
